from __future__ import annotations

from genesis.config import get_config

_TEMPLATE = '''\
# Auto-generated by Genesis MCP
# Tool: {tool_name}
# Description: {description}
# Generated: {timestamp}

{imports}

TOOL_SCHEMA = {{
    "name": "{tool_name}",
    "description": "{description}",
    "inputSchema": {{
        "type": "object",
        "properties": {{
            {properties}
        }},
        "required": [{required}]
    }}
}}


def handler(arguments: dict) -> dict:
    """
    {docstring}
    """
    {body}
    return {{"status": "success", "data": result, "message": "..."}}
'''

_RULES = """\
TOOL FILE RULES (your output will be validated against all of these):

1. Output ONLY raw Python code — no markdown fences, no commentary, no explanation.
2. Module-level TOOL_SCHEMA dict is required (with "name", "description", "inputSchema").
3. Module-level def handler(arguments: dict) -> dict is required.
4. handler MUST return a dict with "status", "data", and "message" keys.
5. On error, return {"status": "error", "data": None, "message": "<description>"}.
6. Tool name MUST be snake_case.
7. Description must be one sentence, plain language.
8. inputSchema MUST be valid JSON Schema with "type" and "properties" keys.
9. Wrap all external API calls in try/except.
10. Validate inputs at the start of handler.
11. Use pathlib.Path for all file operations. Always open files with encoding="utf-8".
12. Do NOT include any top-level code that executes on import (no print(), no function calls).
13. No top-level side effects other than imports, TOOL_SCHEMA, and handler.

ALLOWED IMPORTS ONLY:
- requests
- json
- datetime
- pathlib
- os.path (read-only)
- re
- math
- typing
- urllib.parse

FORBIDDEN (will be rejected):
- subprocess, os.system, eval, exec, compile, __import__
- shutil, socket, ftplib, telnetlib
- Any networking other than requests for HTTPS
"""


def build_generation_prompt(
    description: str,
    name_hint: str | None,
    existing_names: set[str],
) -> str:
    """
    Return the full prompt string to be shown to Claude for tool code generation.
    Claude reads this, generates the code, then calls register_tool with it.
    """
    config = get_config()
    existing_str = ", ".join(sorted(existing_names)) if existing_names else "(none)"

    hint_line = f"\nSuggested tool name: {name_hint}" if name_hint else ""

    return (
        f"Generate a Python tool file for Genesis MCP.\n\n"
        f"DESCRIPTION: {description}{hint_line}\n\n"
        f"EXISTING TOOL NAMES (your tool name must not collide with these): {existing_str}\n\n"
        f"{_RULES}\n\n"
        f"Generate the complete Python file now. Output ONLY the raw Python code, nothing else."
    )
