# Auto-generated by Genesis MCP
# Tool: echo_message
# Description: Returns the input message unchanged.
# Generated: 2026-05-21T00:00:00Z

import json

TOOL_SCHEMA = {
    "name": "echo_message",
    "description": "Returns the input message unchanged.",
    "inputSchema": {
        "type": "object",
        "properties": {
            "message": {"type": "string", "description": "The message to echo."}
        },
        "required": ["message"]
    }
}


def handler(arguments: dict) -> dict:
    """Echo the input message back to the caller."""
    message = arguments.get("message")
    if not message:
        return {"status": "error", "data": None, "message": "Missing required argument: message"}
    return {"status": "success", "data": {"echoed": message}, "message": "Echo successful."}
